- name: variables display from file
  hosts: localhost
  become: no
  vars_files:
    - vars.yaml 
  tasks:
  - name: display variables from file
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}} and duration is {{DURATION}}"