- name: variables from inventory
  hosts: localhost
  become: no
  tasks:
  - name: display variables from inventory
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}} and duration is {{DURATION}}"