- name: conditions
  hosts: localhost
  become: no
  tasks:
  - name: check user exist or not
    ansible.builtin.debug:
      msg: "Hi, I am learning conditions."
    ansible.builtin.command: id nginx